# Generated by Django 3.1.3 on 2021-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_productfeatures_productfeaturesvalidator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='filter_type',
            field=models.CharField(choices=[('radio', 'Радиокнопка'), ('checkbox', 'Чекбокс')], default='checkbox', max_length=20, verbose_name='Тип фильтра'),
        ),
    ]
