# Generated by Django 3.1.3 on 2021-05-20 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210413_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=1, size=None),
            preserve_default=False,
        ),
    ]
